theme: jekyll-theme-minimal
title: Audrey Tjahjadi
logo: "audrey photo.jpg"
description:
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/audrey-tjahjadi/">View My LinkedIn Profile</a>
